Fix/side nav toggle
tiwariav/ye-design pull request #196
Opened 2023-10-21 09:52 UTC by aashishsingla567

1. Formatted input does not change the display value of the input when value prop changes.
2. Toggle props are not passed to SideNav in Page
3.

2023-10-21 10:48 UTC, tiwariav commented
https://62eac0bf72758057b2f38328-yywknibvpy.chromatic.com/?path=/story/components-atoms-formattedinput--preset-value
As I can check in the above story the display does get changed on update, can you re-check or describe the issue a bit more? @aashishsingla567

2023-10-21 10:58 UTC, aashishsingla567 commented
Sorry, I have added the extra description. It is only after you manny type something in the input and then try to change it using setState or something.

2023-10-21 16:20 UTC, tiwariav requested changes

2023-10-22 04:32 UTC, aashishsingla567 commented on src/components/atoms/FormattedInput/FormattedInput.tsx
> +      setFormattedValue(newFormattedValue);
This works in all cases.

2023-12-26 13:20 UTC, closed without merging